In [26]:
import sys 
sys.path.append('../')

import matplotlib.pylab as plt 
%matplotlib inline 

import pandas as pd 
import numpy as np 
from utils.transformation import *

In [2]:
data = pd.read_csv('../examples/jla/data/table_lhs_700.csv').iloc[:,1:]
X = np.array(data.iloc[:,0:6])
y = np.array(data.iloc[:,6])

In [3]:
data.head()

0         1          2         3         4         5            6  \
0  0.478840 -0.348981 -19.087887 -0.031626  0.122513  2.647468 -1139.131867   
1  0.473415 -0.689866 -19.006439 -0.061019  0.115335  2.539736 -1148.448254   
2  0.122278 -0.429985 -19.010809 -0.028724  0.121842  2.721312 -1150.652191   
3  0.391450 -0.911367 -19.081803 -0.027165  0.119317  2.693569 -1150.984717   
4  0.207712 -1.140129 -19.069732 -0.008838  0.116323  2.510581 -1165.514002   

            7           8         9         10         11  
0 -540.264462  697.739940  1.203257  13.978373  33.707679  
1 -543.270806  700.656890 -0.529286  12.729035  32.100642  
2 -542.776911  701.080939  1.338616  13.869142  34.804453  
3 -542.865490  698.107687  1.295719  13.427088  34.386477  
4 -545.265722  698.881710  1.979663  12.897253  31.669658

In [4]:
transform = transformation(X,y)

In [5]:
Xtrain  = transform.Xtransform()

In [6]:
yTrain = transform.yTransform()

In [7]:
transform.yTransformTest(y[0])

3.097121703759709

In [8]:
transform.yInverseTransformTest(transform.yTransformTest(y[0]))

-1139.13186719743

In [9]:
y[0]

-1139.1318671974302

In [10]:
from core.glm import *

In [11]:
# X = np.atleast_2d(np.linspace(0.0, 1.0, 10)).T
# y = X**2

In [12]:
myGLM = GLM(X, y, Var=1E-5)

In [13]:
myGLM.makeTransformation()

In [14]:
D = myGLM.computeBasis(order = 1)

In [15]:
D.shape

(700, 7)

In [16]:
myGLM.regressionPrior(Lambda = 1)

In [17]:
logZ = myGLM.Evidence()

        The log-Evidence is -576921489.85         


In [18]:
post_beta, cov_beta = myGLM.posteriorCoefficients()

In [24]:
X[0]

array([  0.47884041,  -0.34898086, -19.08788704,  -0.03162561,
         0.12251253,   2.64746836])

In [19]:
p = myGLM.prediction(testPoint = X[0])#np.array([0.5]))#

In [29]:
p

In [20]:
p, s = myGLM.prediction(testPoint = X[0], Nsamples=20000)

TypeError: cannot unpack non-iterable NoneType object

In [28]:
plt.hist(s, density = True, bins=20)
plt.axvline(y[0])
plt.show()

NameError: name 's' is not defined

In [23]:
myGLM.post_mean

array([3.09844252])

In [24]:
myGLM.post_var

array([1.00613259e-05])

In [25]:
6.13258649e-08

6.13258649e-08